export const teenRecords = [
  {
    id: 1,
    name: "Ananya Sharma",
    avatar: "https://i.pravatar.cc/150?img=9",
    gender: "Female",
    dob: "2008-05-15",
    age: 16,
    phone: "+91 98765 43210",
    email: "ananya.sharma@email.com",
    city: "Mumbai",
    linked: true,
    relationship: "Daughter",
    created: "2024-06-15",
    lastLogin: "2025-01-14",
    balance: 2450,
    done: 45,
    pending: 3,
    rewards: 8950,
  },
  {
    id: 2,
    name: "Rohan Patel",
    avatar: "https://i.pravatar.cc/150?img=12",
    gender: "Male",
    dob: "2009-08-22",
    age: 15,
    phone: "+91 98123 45678",
    email: "rohan.patel@email.com",
    city: "Bangalore",
    linked: true,
    relationship: "Son",
    created: "2024-07-20",
    lastLogin: "2025-01-15",
    balance: 3200,
    done: 52,
    pending: 2,
    rewards: 10500,
  },
  {
    id: 3,
    name: "Priya Reddy",
    avatar: "https://i.pravatar.cc/150?img=16",
    gender: "Female",
    dob: "2010-03-10",
    age: 14,
    phone: "+91 99876 54321",
    email: "priya.reddy@email.com",
    city: "Hyderabad",
    linked: false,
    relationship: "-",
    created: "2024-08-10",
    lastLogin: "2025-01-13",
    balance: 1800,
    done: 28,
    pending: 5,
    rewards: 5200,
  },
  {
    id: 4,
    name: "Aarav Singh",
    avatar: "https://i.pravatar.cc/150?img=13",
    gender: "Male",
    dob: "2009-11-28",
    age: 15,
    phone: "+91 99234 56789",
    email: "aarav.singh@email.com",
    city: "Delhi",
    linked: true,
    relationship: "Son",
    created: "2024-05-22",
    lastLogin: "2025-01-15",
    balance: 4100,
    done: 68,
    pending: 1,
    rewards: 15200,
  },
];

export const teenTableHeader = [
  { key: "teen", label: "Teen", align: "left" },
  { key: "gender", label: "Gender", align: "left" },
  { key: "dob", label: "DOB", align: "left" },
  { key: "age", label: "Age", align: "left" },
  { key: "phone", label: "Phone", align: "left" },
  { key: "email", label: "Email", align: "left" },
  { key: "city", label: "City", align: "left" },
  { key: "linked", label: "Linked", align: "left" },
  { key: "relationship", label: "Relationship", align: "left" },
  { key: "created", label: "Created", align: "left" },
  { key: "lastLogin", label: "Last Login", align: "left" },
  { key: "balance", label: "Balance", align: "right" },
  { key: "done", label: "Done", align: "center" },
  { key: "pending", label: "Pending", align: "center" },
  { key: "rewards", label: "Rewards", align: "right" },
];

export const parentRecords = [
  {
    id: 1,
    name: "Rajesh Sharma",
    avatar: "https://i.pravatar.cc/150?img=33",
    gender: "Male",
    dob: "1982-11-05",
    age: 42,
    phone: "+91 98765 43210",
    email: "rajesh.sharma@email.com",
    pan: "ABCDE1234F",
    aadhar: "1234 5678 9012",
    kycStatus: "Completed",
    kycType: "Aadhar Upload",
    address: "123, MG Road, Bandra",
    city: "Mumbai",
    teens: 2,
    created: "2024-06-10",
    balance: 15000,
    sent: 25000,
  },
  {
    id: 2,
    name: "Sunita Patel",
    avatar: "https://i.pravatar.cc/150?img=47",
    gender: "Female",
    dob: "1985-07-18",
    age: 39,
    phone: "+91 98123 45678",
    email: "sunita.patel@email.com",
    pan: "XYZAB5678G",
    aadhar: "9876 5432 1098",
    kycStatus: "Completed",
    kycType: "Video KYC",
    address: "456, Koramangala Layout",
    city: "Bangalore",
    teens: 1,
    created: "2024-07-15",
    balance: 22000,
    sent: 18000,
  },
  {
    id: 3,
    name: "Anil Kumar",
    avatar: "https://i.pravatar.cc/150?img=51",
    gender: "Male",
    dob: "1980-03-22",
    age: 44,
    phone: "+91 99112 23344",
    email: "anil.kumar@email.com",
    pan: "LMNOP9876H",
    aadhar: "5678 1234 9876",
    kycStatus: "Pending",
    kycType: "Document Upload",
    address: "789, Jubilee Hills",
    city: "Hyderabad",
    teens: 1,
    created: "2024-08-01",
    balance: 12000,
    sent: 8000,
  },
];

export const choresRecords = [
  {
    id: 1,
    title: "Complete Math Homework",
    description: "Finish chapters 5-7 assignments and submit to teacher",
    parent: "Rajesh Sharma",
    teen: "Ananya Sharma",
    assigned: "2025-01-10",
    dueDate: "2025-01-15",
    completed: "2025-01-14",
    status: "Completed",
    reward: 500,
    verified: "Verified",
  },
  {
    id: 2,
    title: "Clean Room",
    description: "Organize desk, make bed, and vacuum floor",
    parent: "Sunita Patel",
    teen: "Rohan Patel",
    assigned: "2025-01-12",
    dueDate: "2025-01-14",
    completed: "2025-01-13",
    status: "Completed",
    reward: 200,
    verified: "Verified",
  },
  {
    id: 3,
    title: "Practice Piano",
    description: "30 minutes daily practice session",
    parent: "Rajesh Sharma",
    teen: "Ananya Sharma",
    assigned: "2025-01-13",
    dueDate: "2025-01-16",
    completed: "-",
    status: "Pending",
    reward: 300,
    verified: "Pending",
  },
  {
    id: 4,
    title: "Read Chapter Book",
    description: "Complete reading assignment from school library",
    parent: "Anil Kumar",
    teen: "Priya Reddy",
    assigned: "2025-01-08",
    dueDate: "2025-01-12",
    completed: "-",
    status: "Overdue",
    reward: 400,
    verified: "Pending",
  },
  {
    id: 5,
    title: "Help With Groceries",
    description: "Accompany parent to market and carry bags",
    parent: "Sunita Patel",
    teen: "Rohan Patel",
    assigned: "2025-01-14",
    dueDate: "2025-01-15",
    completed: "2025-01-15",
    status: "Completed",
    reward: 150,
    verified: "Verified",
  },
];

export const walletRecords = [
  {
    id: "TXN001234567",
    senderName: "Rajesh Sharma",
    senderRole: "Parent",
    receiverName: "Ananya Sharma",
    receiverRole: "Teen",
    type: "Parent→Teen",
    senderPhone: "+91 98765 43210",
    receiverPhone: "+91 98765 43211",
    amount: 1000,
    mode: "UPI",
    datetime: "2025-01-15 10:30 AM",
    status: "Success",
    notes: "Weekly allowance",
  },
  {
    id: "TXN001234568",
    senderName: "Sunita Patel",
    senderRole: "Parent",
    receiverName: "Rohan Patel",
    receiverRole: "Teen",
    type: "Parent→Teen",
    senderPhone: "+91 98123 45678",
    receiverPhone: "+91 98123 45679",
    amount: 500,
    mode: "Wallet",
    datetime: "2025-01-15 11:45 AM",
    status: "Success",
    notes: "Chore reward payment",
  },
  {
    id: "TXN001234569",
    senderName: "Rohan Patel",
    senderRole: "Teen",
    receiverName: "Sunita Patel",
    receiverRole: "Parent",
    type: "Teen→Parent",
    senderPhone: "+91 98123 45679",
    receiverPhone: "+91 98123 45678",
    amount: 200,
    mode: "Wallet",
    datetime: "2025-01-14 03:20 PM",
    status: "Success",
    notes: "Savings contribution",
  },
  {
    id: "TXN001234570",
    senderName: "Anil Kumar",
    senderRole: "Parent",
    receiverName: "Priya Reddy",
    receiverRole: "Teen",
    type: "Parent→Teen",
    senderPhone: "+91 99112 23344",
    receiverPhone: "+91 99876 54321",
    amount: 750,
    mode: "Card",
    datetime: "2025-01-14 02:15 PM",
    status: "Pending",
    notes: "Book purchase for school",
  },
  {
    id: "TXN001234571",
    senderName: "Rajesh Sharma",
    senderRole: "Parent",
    receiverName: "Aarav Singh",
    receiverRole: "Teen",
    type: "Parent→Teen",
    senderPhone: "+91 98765 43210",
    receiverPhone: "+91 99234 56789",
    amount: 1500,
    mode: "UPI",
    datetime: "2025-01-13 09:00 AM",
    status: "Success",
    notes: "Monthly pocket money",
  },
];

export const ageOptions = [
  { value: "all", label: "All Ages" },
  { value: "13-15", label: "13 to 15 years" },
  { value: "16-18", label: "16 to 18 years" },
];

export const genderOptions = [
  { value: "all", label: "All" },
  { value: "Male", label: "Male" },
  { value: "Female", label: "Female" },
];

export const linkedOptions = [
  { value: "all", label: "All" },
  { value: "linked", label: "Linked" },
  { value: "unlinked", label: "Unlinked" },
];

export const PARENT_TABLE_HEADERS = [
  { label: "Parent", align: "left" },
  { label: "Gender", align: "left" },
  { label: "DOB", align: "left" },
  { label: "Age", align: "left" },
  { label: "Phone", align: "left" },
  { label: "Email", align: "left" },
  { label: "PAN", align: "left" },
  { label: "Aadhar", align: "left" },
  { label: "KYC Status", align: "left" },
  { label: "KYC Type", align: "left" },
  { label: "Address", align: "left" },
  { label: "City", align: "left" },
  { label: "Teens", align: "center" },
  { label: "Created", align: "left" },
  { label: "Balance", align: "right" },
  { label: "Sent", align: "right" },
];

export const CHORES_TABLE_HEADERS = [
  { label: "Chore Title", align: "left" },
  { label: "Description", align: "left" },
  { label: "Parent", align: "left" },
  { label: "Teen", align: "left" },
  { label: "Assigned", align: "left" },
  { label: "Due Date", align: "left" },
  { label: "Completed", align: "left" },
  { label: "Status", align: "left" },
  { label: "Reward", align: "right" },
  { label: "Verified", align: "left" },
];

export const WALLET_TABLE_HEADERS = [
  { label: "Transaction ID", align: "left" },
  { label: "Sender", align: "left" },
  { label: "Receiver", align: "left" },
  { label: "Type", align: "left" },
  { label: "Sender Phone", align: "left" },
  { label: "Receiver Phone", align: "left" },
  { label: "Amount", align: "right" },
  { label: "Mode", align: "left" },
  { label: "Date & Time", align: "left" },
  { label: "Status", align: "left" },
  { label: "Notes", align: "left" },
];
